### ISSUE TITLE
using  cdh --cdh-string cdh532 and --cm-string cm532

### ISSUE THREAD

**Issue by mamatucci** [cloudera/clusterdock#15]
I wanted to use this to recreate an env for the exam

http://www.cloudera.com/training/certification/cca-spark.html
...Each user is given their own CDH5 (currently 5.3.2) cluster pre-loaded...

`
clusterdock_run ./bin/start_cluster cdh --cdh-string cdh532 --cm-string cm532 --dont-start-cluster --primary-node=node-1 --secondary-nodes='node-{2..4}'
`
it does not work

I tried 
clusterdock_run ./bin/start_cluster  --cm-string cm581 --dont-start-cluster --primary-node=node-1 --secondary-nodes='node-{2..4}'
no problem

**Comment by dimaspivak** [comment]
clusterdock requires cluster images to be built (and pushed) before a cluster can be started. Cloudera likely has no plans to go back and create images for CDH 5.3, so this won't be fixed.

**Comment by mamatucci** [comment]
sorry my understanding was that clusterdock would be that smart to deploy and the right version of cm and cdh based on the parameters... so the workaroudn it's to use 
`clusterdock_run ./bin/start_cluster nodebase` and do it manually with rsync and local repository.. ok
cheers

**Comment by dimaspivak** [comment]
clusterdock does deploy the right version of CM/CDH based on the parameters, but the entire workflow of the framework draws a distinction between building a cluster (i.e. creating images) and starting a cluster (i.e. starting and orchestrating containers from those images). For the {{cdh}} topology, we didn't include logic to do the build since it's a bit manual.
