### ISSUE TITLE
Where clusterdock_run command?

### ISSUE THREAD

**Issue by wpengcheng** [cloudera/clusterdock#18]
I did not find where the clusterdock_run command was?

![image](https://cloud.githubusercontent.com/assets/16982786/21963744/cdf2e46c-db7a-11e6-9854-346f70094872.png)

**Comment by dimaspivak** [comment]
It's defined in clusterdock.sh. That's why you need to source that script
first.

On Sun, Jan 15, 2017 at 7:32 AM wpengcheng <notifications@github.com> wrote:

I did not find where the clusterdock_run command was?


[image: image]
<https://cloud.githubusercontent.com/assets/16982786/21963744/cdf2e46c-db7a-11e6-9854-346f70094872.png>




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudera/clusterdock/issues/18>, or mute the thread
