### ISSUE TITLE
URL locations incorrect (Hue, etc.)

### ISSUE THREAD

**Issue by randyzwitch** [cloudera/clusterdock#7]
Continuation of #6 I guess :)

On OSX, once Cloudera Manager is accessed, all of the Web UI links are broken. For example, going to Hue within CM:

<img width="1863" alt="screen shot 2016-08-08 at 10 58 03 am" src="https://cloud.githubusercontent.com/assets/2762787/17484297/2d94581c-5d57-11e6-9edf-9c80a1ca71ae.png">

The configuration thinks the URL should be `http://node-1.testing:8888/`, but I get a DNS error

```
This site can’t be reached

node-1.testing’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

Same thing with Oozie (`http://node-1.testing:11000/oozie`), Impala (`http://node-1.testing:25020/`), etc

**Comment by dimaspivak** [comment]
Yeah, that's a known (and not easily fixable) limitation of using containers for networking. Basically, if you run a browser inside the container, links will work great because you'll have access to container-internal IP addresses and hostnames, but otherwise you're in trouble since Docker intentionally needs to isolate the networking stack within the container from the one on your host. One workaround is to open up a SOCKS 5 proxy to the host running Docker and having your browser use that for DNS resolution. That works fine on Linux hosts, but I've never tried it with Docker for Mac.

**Comment by randyzwitch** [comment]
That's unfortunate for OSX users, but I guess it's not really an issue for you to solve. Guess I'm off to learn more about Docker.

Thanks!
